// archivo que contine la configuracion de cuales campos son editables, de tipo input o relacionales con un select a otras tablas

export const fieldSchemas = {
	products: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "name",
			label: "Nombre del producto",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "price",
			label: "Precio",
			type: "number",
			required: true,
			editable: true,
		},
		{
			name: "stock",
			label: "Stock",
			type: "number",
			required: true,
			editable: true,
		},
		{
			name: "description",
			label: "Descripción",
			type: "textarea",
			editable: true,
		},
		{
			name: "categoryId",
			label: "Categoría",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		{
			name: "supplier_id",
			label: "Proveedor",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		{
			name: "status",
			label: "Estado activo",
			type: "checkbox",
			editable: true,
		},
	],

	suppliers: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "nit",
			label: "NIT",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "name",
			label: "Nombre",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "contact_name",
			label: "Nombre del contacto",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "phone",
			label: "Teléfono",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "email",
			label: "Correo electrónico",
			type: "email",
			required: true,
			editable: true,
		},
		{
			name: "address",
			label: "Dirección",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "status",
			label: "Estado activo",
			type: "checkbox",
			editable: true,
		},
	],

	employees: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "identification_card",
			label: "Cédula",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "name",
			label: "Nombre completo",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "phone",
			label: "Teléfono",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "email",
			label: "Correo electrónico",
			type: "email",
			required: true,
			editable: true,
		},
		{
			name: "salary",
			label: "Salario",
			type: "number",
			required: true,
			editable: true,
		},
		{
			name: "bank_account_number",
			label: "Cuenta bancaria",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "rol",
			label: "Rol",
			type: "select",
			options: [
				{ id: "USER", name: "Usuario" },
				{ id: "ADMIN", name: "Administrador" },
			],
			required: true,
			editable: true,
		},
		{
			name: "branch_store_id",
			label: "Sucursal",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		{
			name: "status",
			label: "Estado activo",
			type: "checkbox",
			editable: true,
		},
	],

	categories: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "name",
			label: "Nombre",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "description",
			label: "Descripción",
			type: "text",
			editable: true,
		},

		{
			name: "status",
			label: "Estado activo",
			type: "checkbox",
			editable: true,
		},
	],

	branchStore: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "name",
			label: "Nombre de la sucursal",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "address",
			label: "Dirección",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "manager_name",
			label: "Nombre del gerente",
			type: "text",
			required: true,
			editable: true,
		},
		{
			name: "number_of_employees",
			label: "Número de empleados",
			type: "number",
			required: true,
			editable: true,
		},
		{
			name: "status",
			label: "Estado activo",
			type: "checkbox",
			editable: true,
		},
	],

	orders: [
		{
			name: "id",
			label: "ID",
			type: "number",
			required: false,
			editable: false,
		},
		{
			name: "order_date",
			label: "Fecha de orden",
			type: "date", // o "date" si usas input tipo fecha
			required: true,
			editable: true,
		},
		{
			name: "supplier_nit",
			label: "Proveedor",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		{
			name: "employees_identification_card",
			label: "Empleado",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		{
			name: "product_name",
			label: "Producto",
			type: "select",
			options: [],
			required: true,
			editable: true,
		},
		// {
		// 	name: "delivery_status",
		// 	label: "Estado de entrega",
		// 	type: "select",
		// 	required: true,
		// 	editable: true,
		// 	options: [
		// 		{ id: "BORRADOR", name: "Borrador" },
		// 		{ id: "EN_ESPERA", name: "En espera" },
		// 		{ id: "APROBADA", name: "Aprobada" },
		// 		{ id: "RECHAZADA", name: "Rechazada" },
		// 		{ id: "RECIBIDA", name: "Recibida" },
		// 	],
		// },
		{
			name: "delivery_status",
			label: "Estado de entrega",
			type: "select",
			required: true,
			editable: true,
			options: [
				{ id: "BORRADOR", name: "Borrador" },
				{ id: "EN_ESPERA", name: "En espera" },
				{ id: "APROBADA", name: "Aprobada" },
				{ id: "RECHAZADA", name: "Rechazada" },
				{ id: "RECIBIDA", name: "Recibida" },
			],
		},
	],
};
